### ISSUE TITLE
onAuthLogout not fired when calling keycloak.logout()

### ISSUE THREAD

**Issue by Bowfish** [panz3r/react-keycloak#11]
I implemented the onEvent handler like this:

```javascript
const keycloak = new Keycloak();

const keycloakConfig = {
  onLoad: 'check-sso'
};

const onTokens = tokens => {
  window.localStorage.setItem('authToken', tokens.token);
};

const onEvent = (event, error) => {
  console.log('onKeycloakEvent', event, error);
  if (typeof error !== undefined) {
    switch (event) {
      case 'onAuthSuccess':
        window.localStorage.setItem('authenticated', keycloak.authenticated);
        break;
      case 'onAuthLogout':
        window.localStorage.setItem('authenticated', false);
        window.localStorage.setItem('authToken', null);
        break;
      case 'onTokenExpired':
        window.localStorage.setItem('authenticated', false);
        window.localStorage.setItem('authToken', null);
        break;
      default:
        break;
    }
  }
};

ReactDOM.render(
  <KeycloakProvider
    keycloak={keycloak}
    initConfig={keycloakConfig}
    onEvent={onEvent}
    onTokens={onTokens}
  >
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </KeycloakProvider>,
  document.getElementById('root')
);
```
The onAuthSuccess is working fine, but when I call `keycloak.logout()` the onAuthLogout event is not fired. Did I get something wrong here?

**Comment by panz3r** [comment]
Hi @Bowfish ,

That's odd, using the following code in the demo of `react-keycloak`, I see the event firing correctly, when calling `logout`;

```js
import { AppRouter } from './routes';

const keycloak = new Keycloak();

class PersistedApp extends React.Component {
  constructor(props) {
    super(props);

    this.tokens = JSON.parse(localStorage.getItem('kcTokens') || '{}');
  }

  onKeycloakEvent = (event, error) => {
    console.log('onKeycloakEvent', event, error);
  }

  onKeycloakTokens = tokens => {
    console.log({ tokens });
    localStorage.setItem('kcTokens', JSON.stringify(tokens));
  }

  render() {
    return (
      <KeycloakProvider
        keycloak={keycloak}
        initConfig={{
          onLoad: 'check-sso',
          ...this.tokens,
        }}
        onEvent={this.onKeycloakEvent}
        onTokens={this.onKeycloakTokens}
      >
        <AppRouter />
      </KeycloakProvider>
    );
  }
}
```

This `PersistedApp` component is used instead of the `App` one in the demo code you can find under `src/demo` of this repo.

Which version of `Keycloak-js` and `react-keycloak` are you using?
The demo is using 
```
"keycloak-js": "^6.0.1",
"react-keycloak": "6.0.4",
```

**Comment by Bowfish** [comment]
That's really odd. I tried your PersistedApp and I can see the logout event firing. 

I'm also using:
```
"keycloak-js": "^6.0.1",
"react-keycloak": "6.0.4"
```
The only difference in my app is that I use `keycloak.login({ redirectUri: 'http://localhost:3000/' })`. Might that be the reason?

**Comment by panz3r** [comment]
I don't think that should be an issue since we're talking about `onAuthLogout` event.
How are you calling `keycloak.logout` method?

Also I'd recommend you to avoid saving the user `token` and `authenticated` inside `localStorage` since you can always retrieve that data from a `keycloak` instance (which is safer and always guaranteed to be in-sync with the actual Keycloak user-session).

**Comment by Bowfish** [comment]
I'm calling it like this:

```javascript
const onClickUserLogout = event => {
    keycloak.logout({ redirectUri: 'http://localhost:3000/logout' });
};
```
The function is called by a button event.

Thanks for the hint. You are right. that is much safer.

**Comment by panz3r** [comment]
I quick test you can make is try to connect `react-keycloak` demo to you Keycloak instance and check if it works as you expect, then have a look at `src/demo/pages/Home.js` to have a look at how I would implement a `logout` on button click.

To try the demo:
- download the repo code,
- run `yarn`, 
- place your `keycloak.json` in the `public` folder 
- run `yarn start`
- try login and logout

**Comment by charan1922** [comment]
I don't think it is an issue, the logout event is working for me.

**Comment by charan1922** [comment]
panz3r, suppose if I logout the user session in  keycloak Admin Console. (Users -> Session -> Logout ) , will the logout event fired? Is there any solution to listen such kind of logout events?

**Comment by panz3r** [comment]
> panz3r, suppose if I logout the user session in keycloak Admin Console. (Users -> Session -> Logout ) , will it fire the logout event? If not Is there any solution to listen such kind of logout events?

Hi @charan1922 , 

I made a couple of tests about your request, and it turned out that `onAuthLogout` is actually called even in the case the user clicks `Logout` from `Keycloak Console`.

If the web-app integrating `react-keycloak` is opened in another tab the event is fired immediately, otherwise the event is fired right before the `onReady` event the next time the web-app is opened.
