### ISSUE TITLE
Token refresh fails with multiple tabs open.

### ISSUE THREAD

**Issue by cody-white** [panz3r/react-keycloak#15]
steps to reproduce (tested in demo app)

Open app in one tab, log in. 
Open in second tab.. trigger a token refresh. 
go back to first tab, trigger a token refresh.. it will fail and the page will either reload, or log out depending on your keycloak init settings. 

Is there a way to get support to work with multiple tabs open? I feel like this should work since data is being shared through local storage?

**Comment by panz3r** [comment]
Hi @cody-white ,

The actual demo app does not sync the tokens through `localStorage`, it is read only on first mount of the App and then ignored.

A possibile solution would be to use something like [React storage hooks](https://github.com/soyguijarro/react-storage-hooks) which acts like an observer on `localStorage`.

**Comment by cody-white** [comment]
@panz3r thanks for the response 

How would using React storage hooks help in this situation? Isn't keycloak only checking provided tokens on Init? could this be a problem with keycloak it self? Or are you suggesting re-calling keycloak init when the local storage changes?

**Comment by panz3r** [comment]
Hi @cody-white ,

Actually, after some more testing with the sample app, I noticed that by setting the `tokens` during `init` (and thus keeping them in sync with `localStorage`) causes many issues with `keycloak` session management.
By commenting out the `...tokens` from `initConfig` I noticed that the tokens are kept in sync directly by `Keycloak` (if it's configured with `onLoad: 'check-sso'`).

You can keep `tokens` inside `localStorage` but I won't recommend that since you can always access the updated tokens via `keycloak` instance.

Let me know if this helps you.

**Comment by cody-white** [comment]
Thanks for looking into this more @panz3r, 

I see, what if one wanted to use `onload: 'login-required'` ? (this is how I tested it) I have the multiple tab problem independent of if the tokens are passed to `initConfig`

**Comment by panz3r** [comment]
Hi @cody-white ,

Could you please try using the `sample` app available on branch [`react-router`](https://github.com/panz3r/react-keycloak/tree/react-router)?

I tested with 2 tabs opened and I can see the tokens being refreshed on both tabs when expired.

**Comment by cody-white** [comment]
@panz3r 

Just tested the `demo` app on that branch. Still have the same problem. Steps I took to clarify

1. Open Tab A, log in. 
2. Open Tab B, user is logged in automatically because of keycloak
3. Wait for Tab A to refresh the token (this succeeds)
4. Wait for Tab B to refresh. This fails it appears the wrong token is being sent in the refresh token request. User is redirected to login screen.

**Comment by panz3r** [comment]
Hi @cody-white ,

> Edit: what just occurred to me in your instance where it is working, is keycloak configured to allow the use of a refresh token more than once? I believe in our instance the refresh token is single use. So my theory is Tab A is using the refresh token, and getting a new token and a new refresh token back, and then Tab B is using the original refresh token, which now is no longer valid, rather than using the new one from Tab A?

As you suggested, that is what's happening, the Keycloak server I'm using is actually configured to not revoke Refresh Tokens.

Since this is not directly an issue of `react-keycloak` (this would happen even if not using this library but `keycloak-js` directly), I'm going to close this issue.

I'd suggest you to update you `Keycloak server` configuration (if you have access to it) to allow multi-tab usage to work.
If you don't want to completely disable `Revoke Refresh Token` you can set `Refresh Token Max Reuse` to an higher value.

Or if you have a better idea on how to handle this issue, just let me know.

**Comment by ahychu84** [comment]
@panz3r Sorry to jump into this conversation so late but I seem to be experiencing the same issue as listed above. What keycloak server configuration should be changed to allows this to work?
