### ISSUE TITLE
How do I start the demo app?

### ISSUE THREAD

**Issue by jplew** [panz3r/react-keycloak#16]
First, thanks for the tool, the custom hook is a nice addition too.

`npm start` fails on the first attempt because it can't find keycloak.json: 
![image](https://user-images.githubusercontent.com/462836/60917971-f26ab280-a246-11e9-9844-545a168f5f45.png)

I got it working only after moving a valid keycloak.json file into the `public` directory. If that's in fact a requirement, it might be worth mentioning in the README.

**Comment by thebetterjort** [comment]
I get the same behavior. Keycloak.json must be public. I prefer to keep it within the code.

**Comment by jplew** [comment]
the path to the json file can also be passed to the constructor like this: `const keycloak = new Keycloak('http://localhost:3030/static/keycloak.json')`

I was unable to get this library working as-is with Next.js due to SSR issues. I can't even import Keycloak's JS adapter (keycloak.js or keycloak-js on npm) without running into "window is undefined" errors on the server. 

I came up with a workaround however, will share the repo when I'm done in case you're interested @thebetterjort

**Comment by thebetterjort** [comment]
I wish the demo was in its own repo. It's a nightmare how its setup.

**Comment by thebetterjort** [comment]
NextJS is exactly where I'm trying to get too.

**Comment by panz3r** [comment]
Hi @jplew ,

Thanks for your feedback, it was much appreciated.
I updated `README.md`  to explain how to run the demo app.

> I was unable to get this library working as-is with Next.js due to SSR issues. I can't even import Keycloak's JS adapter (keycloak.js or keycloak-js on npm) without running into "window is undefined" errors on the server.
I came up with a workaround however, will share the repo when I'm done in case you're interested

This library does not explicitly supports SSR, I never tested that because it was out of the scope of my original use-case.
Nevertheless I'm interested in evaluating if adding the SSR support is feasible without any major change to the actual module implementation, so if you'd like to share your solution or propose a PR I'll gladly review it.

@thebetterjort 
> I get the same behavior. Keycloak.json must be public. I prefer to keep it within the code.

If you don't want to use the `keycloak.json` file, you can pass the required parameters to `Keycloak` instance on creation, see [Keycloak JS setup guide](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter) and you can do as follow
```javascript
const keycloak = Keycloak({
    url: 'http://keycloak-server/auth',
    realm: 'myrealm',
    clientId: 'myapp'
});
```
(for the `demo` app, this code can be placed inside `src/demo/App.js`).

> I wish the demo was in its own repo. It's a nightmare how its setup.

Please note that the `demo` app is not meant to be a starter-kit and thus I don't think having a separate repo would make much sense.
If you need a starter-kit, you'd better off looking for [create-react-app](https://github.com/facebook/create-react-app) or [create-next-app](https://github.com/zeit/create-next-app) (for NextJS).

**Comment by jplew** [comment]
for posterity, here is a link to my Next.js + Keycloak example repo: https://github.com/jplew/next-keycloak
