### ISSUE TITLE
Not call keycloak.init

### ISSUE THREAD

**Issue by NightFox7** [panz3r/react-keycloak#22]
I want to be able to render the dom when the keycloak is ready and the user is authentified. Therefore, I must call the keycloak.init before the render function. Is is possible to add a props to the provider in order to not call the init function of keycloak ? I am also open to other solutions (or workarounds if possibleà

**Comment by panz3r** [comment]
Hi @NightFox7 ,

If I understand correctly you need to "delay" DOM rendering until the user has completed the authentication process on `Keycloak`, if so you can setup `KeycloakProvider` as follow
```js
<KeycloakProvider
  keycloak={keycloak}
  LoadingComponent={<div />}
  initConfig={{
    onLoad: 'login-required',
  }}
>
```
Make sure to place `KeycloakProvider` as the outermost component so that by passing `LoadingComponent` prop the child DOM render will be delayed until `Keycloak` as been initialised.
Since `onLoad` is set to `login-required` as soon as the user get to the app it will be redirected to `Keycloak` (if not already authenticated).

Notice that you can pass any component as `LoadingComponent` so you can display a temporary message while `Keycloak` is being initialised.

Let me know it this helps you.

**Comment by NightFox7** [comment]
Yes that works nicely. Thank you !

**Comment by NightFox7** [comment]
React tries to create the children of the KeycloakProvider even when I add the LoadingComponent. That may lead to some issues when the children depends on some keycloak informations.

**Comment by panz3r** [comment]
Hi @NightFox7 ,

Thanks again for you feedback.

I have an idea on how to implement a better "loading state" check, I'll work on it and report my progress once done.

Basically I'm going to expose a new `prop` for `KeycloakProvider` to allow customising the condition to display `LoadingComponent` (so that it will be possible to add a check on `keycloak.authenticated` property)

**Comment by NightFox7** [comment]
I don't think that will solve the issue. 
I tried this for example:
```js

<KeycloakProvider keycloak={keycloak}
     initConfig={{onLoad: 'login-required'}}
     onToken={onToken}
     onEvent={onEvent}
     LoadingComponent={<div>Loading</div>} children={render()}/>
```
And I noticed that the render function is called even when the loading component is displayed.

**Comment by panz3r** [comment]
I notice 2 little issues in the code you posted:
- Why are you passing `children` as a prop instead of nesting it?
- You are actually calling `render` function that way, thus causing the sub-tree to render

Ideally you should do something like this
```js
      <KeycloakProvider
        keycloak={keycloak}
        initConfig={{
          onLoad: 'login-required',
        }}
        LoadingComponent={<div>Loading...</div>}
      >
        <Child />
      </KeycloakProvider>
```
where `Child` is a component, like this
```js
const Child = () => {
  console.log("I'm a child...");
  return <div />;
};
```

**Comment by NightFox7** [comment]
Indeed, here the Child is rendered after the onAuthSuccess however I got this react error

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by panz3r** [comment]
That's usually happens on a wrong component `import`.
Check that `Child` is actually imported correctly.

**Comment by NightFox7** [comment]
My bad !
You are absolutely correct and now it works like intended. Thank you for your time !
