### ISSUE TITLE
Implement SSR (Server Side Rendering) support

### ISSUE THREAD

**Issue by 3DDario** [panz3r/react-keycloak#27]
**Is your feature request related to a problem? Please describe.**

At the moment React Keycloak does not support SSR. Using this library with server side rendering causes an error (`ReferenceError: window is not defined`).

**Describe the solution you'd like**

Server Side Rendering is a must for a lot of webapps and SPAs. It improves SEO and loading speed improving the overall user experience. For these reasons I think React Keycloak should support server side rendering.

**Additional context**

@jplew reportedly found a solution but, as far as I know, he hasn't shared his implementation yet (#16 - [link to his comment](https://github.com/panz3r/react-keycloak/issues/16#issuecomment-510956640)).

**Comment by jplew** [comment]
@3DDario since there seems to be demand I am going to publish my repo. If you can sit tight a few days I'll have it up asap. 

The `window is not defined` error doesn't come from this repo, per se, but from `keycloak-js`, JBoss Keycloak's official JS adapter: https://www.keycloak.org/docs/6.0/securing_apps/index.html#_javascript_adapter

Their keycloak.js references the `window` object implicitly, and `react-keycloak` bundles keycloak.js as a dependency. Importing `react-keycloak` in Next.js fails because the first server-render pass can't resolve a `window` object, it exists only on the subsequent client-render pass.

The workaround I came up with involves the following:

`const Keycloak =
  typeof window !== 'undefined' ? require('keycloak-js') : null`

Moreover, the keycloak-js adapter sets a cookie in the browser. To avoid Next.js's notorious "flashing" effect, where components and styles blink on the screen suddenly, you have to read the cookie on the server (to render a logged-in state on the server).

Long-story short, there is definitely a way to make the Keycloak JS adapter work with SSR, and it does use code from this repo, but it is beyond the scope of one NPM package alone. A lot of logic needs to be written into the Next app itself. 

One option I thought of was to change the way this library is packaged, so it doesn't bundle `keycloak-js` by default, but lazy-loads it when needed. Haven't had time to experiment with that yet though.

Also, as a heads up, `keycloak-js` version 7 is busted, I had to use 6.0.1: https://github.com/mauriciovigolo/keycloak-angular/issues/153

**Comment by jplew** [comment]
*Update*
here is my solution: https://github.com/jplew/next-keycloak

Hope you find it useful.

**Comment by panz3r** [comment]
Hi @jplew ,

Thanks for the amazing work and for sharing it.
I'll add a reference to it.

**Comment by jplew** [comment]
@panz3r You deserve all the credit for providing this library, thank you!

FYI I will research some more today to see if it's possible to add SSR support directly to react-keycloak.

**Comment by panz3r** [comment]
Hi @jplew ,

Thanks a lot!

I had a look at your code and I think it may be possible to port your changes into `react-keycloak` itself. I'm looking into this myself but I'll need some time to do so.

Keep me posted in case you find a way sooner than me and I'll gladly review your PR.

**Comment by pixelass** [comment]
Any news here? Has this been added to one of the newer versions?

**Comment by panz3r** [comment]
Hi @pixelass ,

Unfortunately it's not yet implemented as part of `react-keycloak`.

I planned a rewrite of this module to allow adding `SSR` support directly but I've yet to start working on it.

**Comment by 3DDario** [comment]
It’s not the proper way to do it but at the moment I’ve been able to get SSR working by changing the value of `libraryTarget` in `config/webpack.config.js`. In particular, I have replaced `umd` with `commonjs2` (as you can see [in this commit](https://github.com/3DDario/react-keycloak/commit/d458d4cad7bf3832e6521b45e23d724e376c06f6)).

This probably makes this library unusable without SSR so I would **not** consider it a solution.

**Comment by pixelass** [comment]
@3DDario I don't see how this would make pages renderable on the server "only" if keycloak is authenticated. The library (keycloak.js) still relies on `document` and can therefore not be executed on the server.  The previously mentioned https://github.com/jplew/next-keycloak uses cookies in order to allow the server to render the page which is also not ideal but works pretty well (with certain drawbacks). I adapted that concept to my project but I'm far from happy as it requires a lot of attention and brings quite some restrictions (especially when animating things on pageLoad) since the mechanism does a force reload (which can only be noticed visually if states change after the initial render, i.e. an animation or render-loops).

react-keycloak would have to do something similar and use a flag to allow SSR only with an auth cookie (or similar). If keycloak would allow SSR this wouldn't even be a problem. IMHO it's their task and without their help all we can do is do server-roundtrips and build workarounds.

That being said, @panz3r I am willing to look into this and contribute if I find something that can be ported back to this library. No promises and definitely not before 2020.

**Comment by panz3r** [comment]
Hi @pixelass ,

Thanks for your feedback, I also had a look at the project at `https://github.com/jplew/next-keycloak` and found a way to port its changes to `react-keycloak`.

The idea I'm working on it's the following:
This project will move to a `monorepo` and will have 3 packages:
- a `core` with all the shared logic.
- a `web`/`spa` with the current binding to be used for SPA apps.
- a `next` with the changes ported from `next-keycloak` repo.

So you'll have to import `@react-keycloak/core` and `@react-keycloak/next` packages to work with NextJS SSR and use the exported components.
Whilst web/SPA apps will need to use the components exported from `@react-keycloak/web`.

This transition will require some time also because I'm moving the codebase to Typescript.

**Comment by panz3r** [comment]
A quick update on this issue.

Today I completed the migration of the repo structure to a `monorepo`  and published the first versions of `@react-keycloak/core` and `@react-keycloak/web` 🎉 

In the next days I'll start working on `@react-keycloak/next` package and example.

**Comment by nicolasmn** [comment]
@panz3r I tested out the `nextjs`  package in the `feature/nextjs-support` branch a bit and it seems to be working fine so far. Could you please release the package to npm asap as the monorepo structure in combination with an unreleased package causes major problems using the package through `npm link`. Thank you and great work!

**Comment by panz3r** [comment]
Hi @nicolasmn,

Thanks for your early feedback on `@react-keycloak/nextjs`, I really appreciate it.

I just released the package with a draft documentation, the package it's still a bit "experimental" and unrefined but now it can be better tested.

I hope to find some time to improve it and release a stable version of the whole new monorepo project as soon as possible.

**Comment by FatalMerlin** [comment]
Hi @panz3r , I just found this repo and the packages and so far it's working really great!

Would it be possible to expose the keycloak instance directly?
Because currently it is only possible to access the instance via hook or HOC, as far as I can tell.

However I am trying to encapsulate e.g. the userProfile (`keycloak.profile`) via [observable ](https://github.com/BeTomorrow/micro-observables), so that I can manage the logic to check if it is loaded and then load it if needed centrally, and then provide the value via observable.

Again, thank you for the great work!

**Comment by panz3r** [comment]
Since `@react-keycloak/nextjs` package has been released and also the refactor to a multi-packages repository is completed, I'm closing this issue.

I really appreciated all the feedbacks about the subject of adding `NextJS` support to the library, also a big thank goes to @jplew for his work which was fundamental to allow me to implement this much requested feature.

The package is still at version `1.0.0-alpha.8` and I'll keep working on it by adding tests and improving the code quality, but in the meanwhile I'd like more people to be able to use it on their projects and reporting back any issue or feedback so that everyone else can benefit from it.

Thanks again.
