### ISSUE TITLE
Support keycloak 7

### ISSUE THREAD

**Issue by oufresh** [panz3r/react-keycloak#32]
Hello,

does this library support keycloak 7?
Thank you very much

oufresh

**Comment by panz3r** [comment]
Hi @oufresh ,

Technically this module does support `keycloak-js` `v7` but unfortunately that version of `keycloak-js` does not currently works due to an internal issue (see here for more details https://issues.jboss.org/browse/KEYCLOAK-11223).

I plan to release version `7.0.0` of `react-keycloak` as soon as the fix for `keycloak-js` is released.

**Comment by oufresh** [comment]
Hi!
I already got that error.
At the moment I use keycloack.js provided by the server we're running.

Thank you

**Comment by panz3r** [comment]
So `react-keycloak' should work as expected.

Once the release for `keycloak-js` will be working, I'll release a new version to keep it in sync.

**Comment by jonkoops** [comment]
I've formally requested that the Keycloak team make a release of the fixed version. We're also waiting for this to introduce new functionality to keycloak-angular.

**Comment by jonkoops** [comment]
Gentlemen, keycloak-js 7.0.1 has been published on NPM. You should be good to go on the update now :smile:

**Comment by panz3r** [comment]
Just released `react-keycloak` version `7.0.1-191016` which bumps required `keycloak-js` version to `7.0.1`.
