### ISSUE TITLE
Refresh the token at some fixed interval rather than on Token expired.

### ISSUE THREAD

**Issue by Techno-than** [panz3r/react-keycloak#45]
I think, there is some problem if we wait till token is expired and then trigger the refresh token api, of some other functional api calls might get returned with 401 error, if the refresh token sent in the api request is already expired. Kind of edge cases, but then we need to handle those 401 by writing interceptors and retrying the api calls once the token refresh is successful.

Can we have simple solution to set the minValidity as a prop in config and then use it for triggering the updateToken method.

**Comment by panz3r** [comment]
Hi @Techno-than ,

Thanks for your feedback.

A quicker solution would be to explicitly call `refreshToken` on the injected `keycloak` instance before making the API call (see official documentation of the method [here](https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter))
```js
keycloak.updateToken(30).then(function() {
    loadData();
}).catch(function() {
    alert('Failed to refresh token');
});
```
(`updateToken` receive a parameter that represent the minimum remaining time required by your call, if the `token` is expiring in less than the passed time it will refresh the token otherwise it won't)

**Comment by nhattextiq** [comment]
Hello @panz3r Thanks for the amazing library. It's easy to setup and use so far.

I'd run into this problem recently, I use axios to make the API requests. I have a general function that compile and trigger axios API calls. However, occasionally the token expires when the API is called and 401 is returned. 
As far as I can tell, the only way to get a `keycloak` instance is through `hook` or `HOC`, how can I use `refreshToken` in a function that is not a function component?
I saw your example here: https://github.com/panz3r/react-keycloak/blob/master/examples/react-router/src/utils/hooks.js, however I don't think I can use it outside of a component. Any hint would be greatly appreciated.

**Comment by panz3r** [comment]
Hi @nhattextiq ,

Thanks for your feedback, recently I've been working using a library similar to `react-keycloak` (but for other authentication providers) and started using a different setup, which I'll start recommending for `react-keycloak` too (I'll update docs and examples as soon as I find some time).
Basically by moving `Keycloak` instance creation to a different file (say `keycloak.js`) placed near the main `App.js`, the instance become available for import around the app.
I suggested this setup to solve another issue but the same could be applied to this use-case, see [here](https://github.com/panz3r/react-keycloak/issues/40#issuecomment-575903380) for a more detailed explanation.

Let me know if this helps you so that I can consider it a viable solution.

**Comment by nhattextiq** [comment]
Hi @panz3r ,

That seems to work, thanks for the pointer. So I have it setup like this for the central api call function.
```
keycloak.updateToken(30).then(() => (
  axios([config])
  .then((response) => {})
  .catch((error) => {})
)).catch(() => {
  console.error('failed to refresh access token')
})
```
It does get refresh automatically before the API is called after 5 minutes of idling.
Cheers.

**Comment by panz3r** [comment]
Hi @nhattextiq ,

Thanks for your quick feedback, I'm glad it solved your issue.

I've update the `README` for the `@react-keycloak/web` package to explain the new project setup and how to access `keycloak` outside of the `react` flow.

Thanks, I'm going to close this issue.
