### ISSUE TITLE
Only refresh token as needed

### ISSUE THREAD

**Issue by LordOfCorners** [panz3r/react-keycloak#47]
I am working with a situation where I don't want the keycloak token to be refreshed every time it expires. We would prefer to refresh the token before loading data that require it. Do you have any recommendations for how we might override the onTokenExpired event so that it doesn't send the update request automatically? or do you think this might be a possible config option to provide in the init? 

Setting keycloak.onTokenExpired to null works to override it but then nothing would get sent to the react-keycloak event handler.

**Comment by panz3r** [comment]
Hi @LordOfCorners ,

Thanks for your feedback.

Despite it's kind of a strange use-case and I wouldn't recommend to do it, I might consider adding a prop (something like `autoRefreshToken`) to the `KeylcoakProvider` component to allow disabling the automatic token refresh since, as you stated, overriding `onTokenExpired` hook would cause `react-keycloak` to not report events correctly.

I'll make an update as soon as possibile and let you know when it's available.

**Comment by laurentC35** [comment]
Hello @panz3r @LordOfCorners  ,

I also have the same need, a new prop `autoRefreshToken` sounds great.

Thanks

**Comment by panz3r** [comment]
Hi @LordOfCorners  and @laurentC35 ,

I just release `@react-keycloak/web` version `1.0.3` which adds the `autoRefreshToken` to `KeycloakProvider`.
To disable the automatic refresh just set this prop to `false`

```jsx
<KeycloakProvider
  keycloak={keycloak}
  autoRefreshToken={false}
>
...
</KeycloakProvider>
```
