### ISSUE TITLE
NextJS App getInitialProps

### ISSUE THREAD

**Issue by mohux** [panz3r/react-keycloak#55]
For some reason, getInitialProps in keycloak/nextjs isnt running at all when I wrap the app with appWIthKeycloak

I think it needs to pass it inside?

**Comment by panz3r** [comment]
Hi @mohux ,

Thanks for your feedback.

Could you please add more details about your issue, for what I tested the `getInitialProps` is getting called as expected for the wrapped component.

**Comment by mohux** [comment]
Yes all pages are calling getInitialProps perfectly except for App Component (_app.js)

please check the pull request I asked, hopefully will make it work

**Comment by mohux** [comment]
https://github.com/panz3r/react-keycloak/pull/57

**Comment by panz3r** [comment]
Hi @mohux and @webdeb, 

Thanks for your feedbacks and contributions.

At the moment I'm evaluating rewriting the whole NextJS integration to be like the `razzle` one since recent changes introduced with `NextJS 9.3` might bring more issues similar to #55 (specifically the introduction of `getStaticProps` and `getServerSideProps` methods which at the moment are ignored when an App is wrapped inside `appWithKeycloak`).

The best solution I can think of is to migrate away from `appWithKeycloak` and instead provide a smarter `SSRKeycloakProvider` component.

Hopefully I might be able to work on this in the coming days.

**Comment by panz3r** [comment]
Hi @mohux and @webdeb,

I just released new versions of `@react-keycloak/nextjs` with the updated integration code.
(versions are `2.0.0-beta.2` for `keycloak-js 9.0.2+` and `1.0.0-beta.1` for `keycloak-js <9.0.2` - notice that they are `beta` and not `alpha` anymore).

This upgrade required major changes and no longer requires messing with `NextApp` `getInitialProps` so this issue should be resolved.

Thanks again for your feedback and support.
