### ISSUE TITLE
React Native support

### ISSUE THREAD

**Issue by SrMouraSilva** [panz3r/react-keycloak#63]
Hello, congratulations on the project. I use it in a react web application. 
I would like to request the support for react native applications.

**Comment by panz3r** [comment]
Hi @SrMouraSilva ,

Thanks for your feedback.

Although `keycloak-js` module does seem to offer a way to be used in the context of mobile hybrid app (specifically `cordova`-based ones as per Keycloak own docs [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#hybrid-apps-with-cordova)), I hardly doubt it would work well with `react-native` and because this module fully relies on `keycloak-js` to interact with Keycloak I won't be able to add `React Native` support to it.

I'd suggest you to have look at [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth), I used it for some React Native projects and found it easy to integrate into an app and make it work with Keycloak (an example configuration for Keycloak is also provided - see [here](https://github.com/FormidableLabs/react-native-app-auth/blob/master/docs/config-examples/keycloak.md)).

Thanks again and let me know if it helps you.

**Comment by SrMouraSilva** [comment]
> I hardly doubt it would work well with react-native and because this module fully relies on keycloak-js to interact with Keycloak I won't be able to add React Native support to it.

Ow, it's true!

> I'd suggest you to have look at react-native-app-auth, I used it for some React Native projects and found it easy to integrate into an app and make it work with Keycloak (an example configuration for Keycloak is also provided - see here).

I use this library, however I have to be careful to store the tokens (which I have already done, it's ok) and to update the active token. In my implementation, I only go after a new token when someone makes a request and the current one is expired. There is a bug that sometimes the token is inactive and no requests work in the lifetime of that token.

I remembered this library (which it takes care of updating the token) and thought about using. I remember that I had already tried to install it and the keycloak.js, but it hadn't worked ... I didn't realize that the problem is in the third library (the official Keycloak js library).

Do you have any tips on token renewal?

Thanks for the feedback!

**Comment by panz3r** [comment]
Hi @SrMouraSilva ,

> Do you have any tips on token renewal?

This is a common use-case and usually I'd implement 2 interceptors around the API calls (one before every request and one to handle `401` responses) to try refreshing the token.

Basically you do a token refresh before every call to your BE (when using a "smart" Auth library it would automatically check if the token is expired or not - so to avoid refreshing a valid token) or try with a different token in case a `401` is returned by the BE (this is not always desirable but depends on the use-case 😬 ).

The actual implementation also depends on the libraries you are using (e.g. `axios`/`fetch`, `redux-saga`, etc...)

**Comment by SrMouraSilva** [comment]
Hello, @panz3r 

I implemented a interceptor like:
> when using a "smart" Auth library it would automatically check if the token is expired or not - so to avoid refreshing a valid token

But sometimes a 401 occurs for an unknown reason (bug?). I even put a threshold, but sometimes it occurs and it appears intermittently
> or try with a different token in case a 401 is returned by the BE (this is not always desirable but depends on the use-case grimacing ).

I appreciate your suggestion about 401, I will implement too
>  (this is not always desirable but depends on the use-case :grimacing: )

----

Do I close this issue?
It's ok in my use case.

**Comment by panz3r** [comment]
Hi @SrMouraSilva ,
Glad I could be of help.

Closing this issue.

**Comment by panz3r** [comment]
With the help of @IronTony , we implemented a React Native adapter that works like `@react-keycloak/web`, the project can be found at [react-keycloak/react-native-keycloak](https://github.com/react-keycloak/react-native-keycloak).
