### ISSUE TITLE
Return singleton for getKeycloakInstance

### ISSUE THREAD

**Issue by webdeb** [panz3r/react-keycloak#65]
**Is your feature request related to a problem? Please describe.**

We have an **apolloClient** setup with the **setContext** approach to add the token on every request to the headers. The problem is, you don't have the possibility to use Hooks in **setContext**

**Describe the solution you'd like**

So, my Idea was (and this what I am doing right now, with a fork) is return the same **keycloak** instance for every **getKeycloakInstance** call.

Thats basically what it is, it enforces recreation of the instance, if you pass in the  **initOptions**
```
let instance
export const getKeycloakInstance = initOptions => {
  if (typeof window === "undefined") {
    return KeycloakStub
  }

  instance = (!initOptions && instance) || new Keycloak(initOptions)
  return instance
}

```

For the context, this is the apolloClient setup I am using with my fork

```
const contextLink = setContext((_, context) => {
  const kc = getKeycloakInstance()

  return {
    headers: {
      ...(kc.token ? { Authorization: "Bearer " + kc.token } : {}),
    },
  }
})

export default withApollo(({ initialState }) => {
  const GRAPHQL_URI = initialState
    ? initialState.GRAPHQL_URI
    : process.env.GRAPHQL_URI

  return new ApolloClient({
    link: contextLink.concat(createHttpLink({ uri: GRAPHQL_URI })),
    cache: new InMemoryCache().restore(initialState || { GRAPHQL_URI }),
  })
})
```

**Comment by panz3r** [comment]
Hi @webdeb ,

Thanks for your feedback, actually that sounds as a great idea.

In the `@react-keycloak/web` package there's a similar feature (based on the suggested setup) which is described in the README [here](https://github.com/panz3r/react-keycloak/tree/master/packages/web#external-usage-advanced).
In the `@react-keycloak/nextjs` package that same solution wouldn't work because the `keycloak` instance is managed within the module (because of the difference between server- and client-side).

If you'd like to open a PR with the above changes, I'll gladly review it.

**Comment by webdeb** [comment]
I am glad you like the idea, I'll try to find the time to do it, actually we are in a very tight timeline right now, but I've to try, because its not optimal to use the fork.

**Comment by webdeb** [comment]
Maybe you already have some suggestions regarding the above snipped, so we don't have to go through any feedback loops?

**Comment by panz3r** [comment]
Hi @webdeb ,

I just released version `2.0.0-beta.4` of `@react-keycloak/nextjs` package which contains the updated `getKeycloakInstance` method.

The implementation is quite similar to the one you proposed but instead of relying on the presence of `initOptions` uses a dedicated param (`recreate`) to require a new instance.

The TS signature is as follow
```ts
export function getKeycloakInstance(keycloakConfig: KeycloakConfig, recreate: boolean = false
): KeycloakInstance
```
Notice that `recreate` is optional and defaults to `false`.

The method is exported from the main package and should be available as 
```js
import { getKeycloakInstance } from '@react-keycloak/nextjs`;
```

Let me know if this works for you.

**Comment by webdeb** [comment]
Wow, thank you @panz3r 
I'll try it out these days, just need to finish some current stuff.

**Comment by webdeb** [comment]
Hi @panz3r 
It's working great on the client!
However, on the backend, its not updating the token, as far as I can say.
In my case it's a custom express server, so I guess this is where the problem comes from.

**Comment by webdeb** [comment]
One more info: I am using `getKeycloakInstance`, I guess, that I just got the cached version.
Maybe I should just use the cookie directly?

**Comment by panz3r** [comment]
Hi @webdeb ,

Thanks for your feedback.

To answer your question, the logic to retrieve the cookies from the request should be implemented and the result passed to the `Persistors.Cookies` class (see the package `README` [here](https://github.com/panz3r/react-keycloak/tree/master/packages/nextjs#setup-nextapp) for more info).

The current implementation of the `Persistors.Cookies` does not try to set the cookies when running server-side because the Keycloak instance returned is the 'stub' one (so at the moment there's no way to update the tokens server-side).

Could you please check if the cookies are retrieved correctly from the `request` and forwarded to `Persistors.Cookies` as expected (with the keys `kcToken` and `kcIdToken`)?

**Comment by webdeb** [comment]
> Could you please check if the cookies are retrieved correctly from the request and forwarded to Persistors.Cookies as expected (with the keys kcToken and kcIdToken)?

Well, yes. But the stub is created once and the token inside it, is the token of the first user, requests for other users will get the same instance.

**Comment by panz3r** [comment]
Hi @webdeb ,

Thanks for the clear report, this sounds like a major issue, I'll release a fix as soon as possible.

I'll update you when it's released so you can test if the issue is resolved.

**Comment by webdeb** [comment]
@panz3r I am not sure how this could be resolved, since the object is just kept in memory.
Like I said its an express server. So any global object will be available the whole process life-time.
I though about recreating the instance for each request, but anyway race conditions are very possible.
I guess the singleton on the server is not possible

**Comment by panz3r** [comment]
Hi @webdeb ,

Just released a new version of `@react-keycloak/nextjs` which contains a possible fix for the above issue.
The `keycloakStubInstance` now is refreshed every time the `SSRKeycloakProvider` is rendered (that should always be the case on server-side), this can still cause possible `token-leakage` in some cases but should be better than before.

Let me know if it fixes your issue and if you have any better idea on how to solve the `token-leakage` issue.

**Comment by webdeb** [comment]
> this can still cause possible token-leakage in some cases but should be better than before.
yeah, but its not possible to avoid that leak and it could potentially be a serious security issue.

Imagine you have to call two services on a route, one after the other

1. you make the request, your token is set globally, you call the fist api with your token
2. another user comes in, his token is now set globally
3. you got your result back and you are doing another call (but now its using your another token)

My final solution is to not rely on globals, instead I found a way to access the context where I previously used the getInstance function, and now I am just using the `kcToken` cookie.

**Comment by panz3r** [comment]
Hi @webdeb ,

Thanks for your feedback and sorry for the late answer.

I added a section dedicated to this feature to `@react-keycloak/nextjs` docs with reference to the possibile issues.
